### ISSUE TITLE
How can I be allowed to add a Danish translation of the languagefile?

### ISSUE THREAD

**Issue by Techek** [srollinet/Countries#2]
I have already created a complete list of the countries translated to Danish, I have cloned and created a new branch and run tests, but I am not allowed to push the feature-branch.

Can you help?

**Comment by srollinet** [comment]
Hi!

Thanks for the translations. You will have to create a Pull Request to merge your branch in the repo.
https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

Note: I have not updated the country list since a few years, so I don't know if it is up to date with the official country list. If you are interested, I can update them
